### ISSUE TITLE
zone bypass switches

### ISSUE THREAD

**Issue by tinuva** [Cinntax/pyenvisalink#23]
When is zone bypass switches coming back to HA?

Is there a workaround to enable them on the latest version?

**Comment by ufodone** [comment]
@tinuva I'm sorry I haven't had a chance to get these re-enabled.  Because the changes were causing problems for people with certain alarm panel setups, I needed to add a way to disable them via config.  Unfortunately, the HA maintainers aren't accepting new config changes for integrations that don't use the newer config flow.  So I can't get the feature re-enabled until I make the config flow changes.  I'm not familiar with that system and when I had a look, I didn't see a quick way to do the upgrade and I've just not been able to make the time for it yet.  

The bulk of the code still exists in the latest HA releases but the only workaround to re-enable the switches would involve modifying the source file - which would get stomped every time you upgrade to a newer HA version.

For my own setup I've just hacked up a custom component using the same code with with a different name for now.

[This](https://github.com/home-assistant/core/commit/49a41ebe14b047dd4f73d023a9ab8c44312a6555) is the change that disabled the switches.  Reverting `__init__.py` to [this](https://github.com/home-assistant/core/blob/10efeb2935942277205605445c6cb731f85e6f07/homeassistant/components/envisalink/__init__.py) version should re-enable the switches. 

Sorry I don't have better news.

**Comment by tinuva** [comment]
@ufodone thank you for the reply!

To be honest, I am not surprised. That has been the core team's stance for a while, that new integrations and updates to current integrations where configs are concerned, must use the config flow.

Also understand you do not have time. The work around seems fine for now I think.

**Comment by tinuva** [comment]
~~How do I make this work as a custom component. Ignoring the changes required to get bypass switches in, I am unable to make it work as a custom component.~~

Edit: scratch that. I think I figured it out. Copied the integration over from core (version 2022.2.4 I was on) to custom components, added a version to the manifest and seems to work now after upgrading.

**Comment by ufodone** [comment]
Given how unable I've been to find time to investigate the config flow stuff, I might look to create a HACS version for now to make it easier for others waiting for this feature as well as get away from my hacked up custom component version.  I think that should be pretty quick.  I'd still like to get these changes back into an official release but I just don't know when I'll be able to do that.

**Comment by tinuva** [comment]
My suggestion is to get someone else onboard to help with the config flow stuff. Someone who has experience with it.

For example, the recent Goodwe integration, someone else was interested to get it as official integration and he had the experience with the config flow part. He was able to do that part for the original goodwe author.

**Comment by ufodone** [comment]
@tinuva In case you're interested, I've created a temporary HACS repo that has the zone bypass switches enabled.

https://github.com/ufodone/dscalarm/

**Comment by ufodone** [comment]
Closing this issue out as this feature is available in [envisalink_new](https://github.com/ufodone/envisalink_new).  Hope to get it back into HA officially at some point.
